#!/bin/sh

#Variables
CUCMIP=$1
SIPName=$2

# Input file
FILE='/usr/local/nagios/libexec/check_sip/'$1'_sip_status'

# How many seconds before file is deemed "older"
OLDTIME=300

# Get current and file times
CURTIME=$(date +%s)
FILETIME=$(stat $FILE -c %Y)
TIMEDIFF=$(expr $CURTIME - $FILETIME)

# Get SIP status
STATUS=$(cat $FILE | grep $SIPName | cut -d':' -f3)

# Check if file older
if [ $TIMEDIFF -gt $OLDTIME ]; then
   echo "Parameters UNKNWON - status is not up to date";
   exit 3;
elif [[ $STATUS == "Registered" ]]; then
   echo "Parameters OK - $SIPName is UP";
   exit 0;
else
   echo "Parameters CRITICAL - $SIPName is DOWN";
   exit 2;
fi
